
- Neues Framing:
  - Wir delineaten wand & andere uncertainty
  - Später kann man das dann (hoffentlich) mit Gradual Typing "retten"
  - Grund:
    - Keine Eliminatoren: Viele Programme nicht typbar
    - Eliminatoren: Progress & Preservation die
    - _gradual typing is forced_
- Contributions
  - P&X with an unknown type
  - New lookup relation
  - Stumps that allow to remove guessing
  - Unification with strong metatheory
  - Rows form a trace monoid
- Zustand: Beweise für Systeme durch
  - Sound&Complete: Für L1 und L2
  - Termination für Unification
  - Principality für ein Beispiel (qualified schemes are forced)
  - Incompleteness mit drei Gründen:
    - Wand: 3 Beispiele:
      - (l: τ)     ≐ (a | b)   : can't be hosted in one side
      - (α | l: τ) ≐ (l: τ | β): No unique since both could hold some fields but shadowing makes it asymmetric
      - (α | l: τ) ≐ (α | l: τ): Same problem
    - Inference:
      - T-let is monotone only for expressions that have unresolved keys
      - Unrestricte T-★-intro
    - FC-labels:
      - ?
- Ongoing
  - Thesis text schreiben, AI legt die foundation
- Fragen
  - Ist AI assisted work so far okay?
  - Sind das genügend contributions?
  - Was wünscht er sich noch?
