#import "./functions.typ": *

// Comparison of the record/row literature against the requirements of this thesis.
// Legend:  ● yes / full support   ◐ restricted, derived or only in an instance
//          ·  no / not addressed   ? not stated by the paper
//
// The papers are ordered chronologically.  "This work" is the calculus of this
// thesis and is always the last row.
//
// Provenance: every cell was checked against the paper's own text, except the
// two Rémy rows -- the HAL scans in research/Records/ have broken font
// encodings and could not be searched; those two rows follow the standard
// characterisation in the literature and should be re-checked against a clean
// copy before the table goes into the thesis.

#let rc-y = $●$                              // yes
#let rc-p = $◐$                              // partial / derived / instance-only
#let rc-n = text(fill: luma(180), $·$)       // no
#let rc-u = text(fill: luma(140), [?])       // not stated

#let rc-hd(body) = table.cell(align: bottom, text(
  size: 7pt,
  weight: "bold",
  body,
))
#let rc-nt(body) = text(size: 7pt, style: "italic", body)
#let rc-pa(body) = table.cell(align: left, text(size: 8pt, body))
#let rc-gr(n, body) = table.cell(colspan: n, fill: luma(240), text(
  size: 8pt,
  weight: "bold",
  body,
))
// ---------------------------------------------------------------------------
// Table A -- which record operations does the system actually type?
// ---------------------------------------------------------------------------
#let records-ops = table(
  columns: (7.2em,) + (auto,) * 10,
  align: center + horizon,
  inset: 4pt,
  stroke: 0.4pt + luma(200),

  rc-hd[System],
  rc-hd[Ext.],
  rc-hd[Upd.],
  rc-hd[Del.],
  rc-hd[Sym. ‖],
  rc-hd[Asym. ‖],
  rc-hd[Collision],
  rc-hd[Dup. labels],
  rc-hd[FC labels],
  rc-hd[Variants],
  rc-hd[$λ x y. (x ‖ y).l$],

  rc-gr(11)[Classic record calculi],

  rc-pa[Cardelli & Mitchell '91 @operations_on_records],
  rc-y,
  rc-y,
  rc-y,
  rc-n,
  rc-n,
  rc-nt[error],
  rc-n,
  rc-n,
  rc-n,
  rc-n,

  rc-pa[Wand '91 @concat4multiinher],
  rc-y,
  rc-p,
  rc-n,
  rc-n,
  rc-y,
  rc-nt[right wins],
  rc-n,
  rc-n,
  rc-n,
  rc-p,

  rc-pa[Harper & Pierce '91 @symm_concat],
  rc-p,
  rc-p,
  rc-y,
  rc-y,
  rc-n,
  rc-nt[error],
  rc-n,
  rc-n,
  rc-n,
  rc-n,

  rc-pa[Rémy '92 @concat4free],
  rc-y,
  rc-y,
  rc-y,
  rc-y,
  rc-y,
  rc-nt[both, encoded],
  rc-n,
  rc-n,
  rc-y,
  rc-p,

  rc-pa[Rémy '93 @remy_natural_ml],
  rc-y,
  rc-y,
  rc-y,
  rc-n,
  rc-n,
  rc-nt[n/a],
  rc-n,
  rc-n,
  rc-y,
  rc-n,

  rc-pa[Ohori '95 @ohori1995polymorphic],
  rc-n,
  rc-y,
  rc-n,
  rc-n,
  rc-n,
  rc-nt[n/a],
  rc-n,
  rc-n,
  rc-y,
  rc-n,

  rc-pa[Gaster & Jones '96 @gaster_jones],
  rc-y,
  rc-p,
  rc-y,
  rc-n,
  rc-n,
  rc-nt[error],
  rc-n,
  rc-p,
  rc-y,
  rc-n,

  rc-pa[Sulzmann '97 @designing_record_systems],
  rc-y,
  rc-y,
  rc-y,
  rc-y,
  rc-n,
  rc-nt[error],
  rc-n,
  rc-y,
  rc-y,
  rc-n,

  rc-gr(11)[Row polymorphism with labels],

  rc-pa[Leijen '04 @fc_labels],
  rc-y,
  rc-y,
  rc-y,
  rc-n,
  rc-n,
  rc-nt[error],
  rc-n,
  rc-y,
  rc-y,
  rc-n,

  rc-pa[Leijen '05 @extensible_recs],
  rc-y,
  rc-y,
  rc-y,
  rc-n,
  rc-n,
  rc-nt[keep both],
  rc-y,
  rc-n,
  rc-y,
  rc-n,

  rc-pa[Chlipala '10 @ur],
  rc-y,
  rc-p,
  rc-y,
  rc-y,
  rc-n,
  rc-nt[error],
  rc-n,
  rc-y,
  rc-y,
  rc-n,

  rc-pa[Paszke & Xie '23 @extensible_tabular],
  rc-y,
  rc-p,
  rc-y,
  rc-y,
  rc-n,
  rc-nt[keep both],
  rc-y,
  rc-y,
  rc-n,
  rc-n,

  rc-gr(11)[Row theories / qualified types],

  rc-pa[Morris & McKinna '19 @rose],
  rc-y,
  rc-y,
  rc-y,
  rc-y,
  rc-y,
  rc-nt[parametric],
  rc-y,
  rc-n,
  rc-y,
  rc-y,

  rc-pa[Hubers & Morris '23 @generic_with_extensible],
  rc-y,
  rc-y,
  rc-y,
  rc-y,
  rc-p,
  rc-nt[parametric],
  rc-p,
  rc-y,
  rc-y,
  rc-p,

  rc-pa[Hubers et al. '25 @extensible_rec_funcs],
  rc-y,
  rc-y,
  rc-y,
  rc-y,
  rc-p,
  rc-nt[parametric],
  rc-p,
  rc-y,
  rc-y,
  rc-p,

  rc-pa[Toohey et al. '26 @extensible_data_adhoc],
  rc-y,
  rc-y,
  rc-y,
  rc-y,
  rc-p,
  rc-nt[parametric],
  rc-p,
  rc-y,
  rc-y,
  rc-p,

  rc-gr(11)[This thesis],

  rc-pa[Soft records for Nix],
  rc-y,
  rc-y,
  rc-y,
  rc-y,
  rc-y,
  rc-nt[right wins],
  rc-y,
  rc-y,
  rc-n,
  rc-y,
)

// ---------------------------------------------------------------------------
// Table B -- what does the metatheory buy, and at what price?
// ---------------------------------------------------------------------------
#let records-meta = table(
  columns: (7.2em,) + (auto,) * 8,
  align: center + horizon,
  inset: 4pt,
  stroke: 0.4pt + luma(200),

  rc-hd[System],
  rc-hd[Constraint device],
  rc-hd[Inference],
  rc-hd[Principal],
  rc-hd[Solver given],
  rc-hd[Subtyping],
  rc-hd[Compilation],
  rc-hd[Mechanized],
  rc-hd[Dyn. fallback],

  rc-pa[Cardelli & Mitchell '91 @operations_on_records],
  rc-nt[subtyping + $forall_(<:)$],
  rc-n,
  rc-n,
  rc-y,
  rc-y,
  rc-n,
  rc-n,
  rc-n,

  rc-pa[Wand '91 @concat4multiinher],
  rc-nt[row variables],
  rc-y,
  rc-nt[finite sets],
  rc-y,
  rc-n,
  rc-n,
  rc-n,
  rc-n,

  rc-pa[Harper & Pierce '91 @symm_concat],
  rc-nt[lacks/has annot.],
  rc-n,
  rc-n,
  rc-y,
  rc-n,
  rc-n,
  rc-n,
  rc-n,

  rc-pa[Rémy '92 @concat4free],
  rc-nt[presence flags],
  rc-y,
  rc-y,
  rc-y,
  rc-n,
  rc-p,
  rc-n,
  rc-n,

  rc-pa[Rémy '93 @remy_natural_ml],
  rc-nt[presence flags],
  rc-y,
  rc-y,
  rc-y,
  rc-n,
  rc-y,
  rc-n,
  rc-n,

  rc-pa[Ohori '95 @ohori1995polymorphic],
  rc-nt[kinded quant.],
  rc-y,
  rc-y,
  rc-y,
  rc-n,
  rc-y,
  rc-n,
  rc-n,

  rc-pa[Gaster & Jones '96 @gaster_jones],
  rc-nt[lacks predicates],
  rc-y,
  rc-y,
  rc-y,
  rc-n,
  rc-y,
  rc-n,
  rc-n,

  rc-pa[Sulzmann '97 @designing_record_systems],
  rc-nt[HM(X)],
  rc-y,
  rc-y,
  rc-n,
  rc-n,
  rc-n,
  rc-n,
  rc-n,

  rc-pa[Leijen '04 @fc_labels],
  rc-nt[row-equality pred.],
  rc-y,
  rc-y,
  rc-y,
  rc-n,
  rc-y,
  rc-n,
  rc-n,

  rc-pa[Leijen '05 @extensible_recs],
  rc-nt[row equivalence],
  rc-y,
  rc-y,
  rc-y,
  rc-n,
  rc-y,
  rc-n,
  rc-n,

  rc-pa[Chlipala '10 @ur],
  rc-nt[disjointness],
  rc-p,
  rc-n,
  rc-n,
  rc-n,
  rc-y,
  rc-n,
  rc-n,

  rc-pa[Paszke & Xie '23 @extensible_tabular],
  rc-nt[row unification],
  rc-y,
  rc-p,
  rc-y,
  rc-n,
  rc-n,
  rc-n,
  rc-n,

  rc-pa[Morris & McKinna '19 @rose],
  rc-nt[row theories],
  rc-y,
  rc-y,
  rc-n,
  rc-n,
  rc-y,
  rc-n,
  rc-n,

  rc-pa[Hubers & Morris '23 @generic_with_extensible],
  rc-nt[row theories],
  rc-n,
  rc-n,
  rc-n,
  rc-n,
  rc-n,
  rc-y,
  rc-n,

  rc-pa[Hubers et al. '25 @extensible_rec_funcs],
  rc-nt[row theories],
  rc-n,
  rc-n,
  rc-n,
  rc-n,
  rc-n,
  rc-y,
  rc-n,

  rc-pa[Toohey et al. '26 @extensible_data_adhoc],
  rc-nt[rows + classes],
  rc-n,
  rc-n,
  rc-n,
  rc-p,
  rc-y,
  rc-y,
  rc-n,

  rc-pa[Soft records for Nix],
  rc-nt[lookup stumps],
  rc-y,
  rc-y,
  rc-y,
  rc-n,
  rc-u,
  rc-p,
  rc-y,
)

#records-ops
#records-meta
#bib
