#let depr(t) = text(fill: orange, t)
#let comparison = figure(caption: "Garnix and NixLang Features" ,table(
  columns: (1fr, 2fr, auto, auto),
  inset: 10pt,
  align: (left, left, center, center),
  table.header([*Feature*], [*Example*], [*Garnix*], [*NixLang*]),
  table.cell(colspan: 4)[*Basic Types*],
  [Boolean], `true`,                              `●`, `◌`,
  [String], `"single line"`,                      `●`, `◌`,
  [Ident String], `'' multi \n line ''`,          `●`, ` `,
  [Number], `1.23, 3`,                            `●`, `◌`,
  [Path], [./home/user],                          `●`, ` `,
  depr[Uri], `https://github.com`,                    `` , ` `,
  [Array], `[ 1 2 ]`,                             `●`, `◌`,
  [Record], `{a = 1; b = "2";}`,                  `●`, `◌`,
  [Rec-Record], `rec {a = b; b = a;}`,            `●`, `◌`,
  [Searchpath], `<nixpkgs>`,                      `●`, ` `,
  [Null], `null`,                                 `●`, `◌`,
  table.cell(colspan: 4)[*Language Constructs*],
  [Let-Bindings], `let a = 1; in ()`,             `●`, `◌`,
  depr[Let-Record-Bindings], `let {a = 1;} in ()`,` `, `◌`,
  [Function], `x: x + 1`,                         `●`, `◌`,
  [Functor], `x: x + 1`,                          ` `, `◌`,
  [Pattern-Functions], `{ a }: a`,                `●`, `◌`,
  [Open-Pattern], `{ a, ... }: a`,                `●`, `◌`,
  [Default-values], `a ? 2: a`,                   `●`, `◌`,
  [Global-bindings], `{a} @ b: b.a`,              `●`, ` `,
  [Conditionals], `if cond then null else 1`,     `●`, `◌`,
  [Inherit], `inherit (players) bob;`,            `●`, `◌`,
  [With], `with {a = 1;}; a`,                     `●`, `◌`,
  [Dynamic Lookup], `{a = 1;}.${"a"}`,            ` `, ` `,
  [String-Interpolation], `The name is: ${name}`, ` `, ` `,
  [Assert], `assert false;`,                      `●`, ` `,
  table.cell(colspan: 4)[*Operators*],
  [Arithmetic], `1 + 2 / 3 * 4`,                  `●`, ` `,
  [Logic], `true | false & true → false`,         `●`, ` `,
  [Lookup], `{ a = 2;}.a`,                        `●`, ` `,
  [Has-Attr], `{ a = 2;}.a`,                      `●`, ` `,
  [Or], `{a = 2;}.b or 5`,                        `●`, ` `,
  [Array-Concat], `[1 2] ++ [3 4]`,               `●`, ` `,
  [Record-Concat], `{a = 2;} // {b = 3;}`,        `●`, ` `,
  [Pipe], `|> <|`,                                ` `, ` `,
))
